name: my_ceo
description: A new Flutter application.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  characters: ^1.0.0
  flutter_tindercard: ^0.1.9
  tcard: ^1.2.2
  ff_navigation_bar: ^0.1.5
  font_awesome_flutter: ^8.8.1
  typicons_flutter: ^0.3.1
  line_icons: ^0.2.0
  rflutter_alert: ^1.0.3
  cloud_firestore: ^0.13.7
  firebase_core: ^0.4.5
  firebase_auth: ^0.16.1
  modal_progress_hud: ^0.1.3
  google_sign_in: ^4.5.1




dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true


  assets:
    - images/


